import { Pool } from "pg";
import { runtimeEnv } from "@/lib/runtime-env";
import type { ResearchSession } from "./contracts";

export type Workspace = { id: string; name: string; description: string; createdAt: string };
export type CitationStyle = "APA" | "MLA";
export type PaperMetadata = { authorName: string; courseName: string; instructorName: string; date: string; paperType?: "research-paper" | "essay" };
export type WorkspacePaper = { id: string; workspaceId: string; title: string; contentMarkdown: string; citations: unknown[]; sourceSessionIds: string[]; citationStyle: CitationStyle; targetWordCount: number; paperMetadata: PaperMetadata; parentPaperId?: string; revisionNumber: number; createdAt: string };
export type WorkspaceRun = { id: string; question: string; status: ResearchSession["status"]; createdAt: string };
export type WritingProfile = { id: string; name: string; authorName: string; courseName: string; instructorName: string; citationStyle: CitationStyle; targetWordCount: number };

let pool: Pool | undefined;
function database() { const connectionString = runtimeEnv("DATABASE_URL"); if (!connectionString) return undefined; pool ??= new Pool({ connectionString }); return pool; }
export async function saveSession(session: ResearchSession, ownerUid: string, workspaceId?: string): Promise<{ persisted: boolean; reason?: string }> {
  const db = database(); if (!db) return { persisted: false, reason: "DATABASE_URL is not configured; session exists only for this request." };
  if (workspaceId) { const workspace = await db.query("SELECT 1 FROM research_workspaces WHERE id = $1 AND owner_uid = $2", [workspaceId, ownerUid]); if (!workspace.rowCount) throw new Error("Workspace not found."); }
  await db.query("DELETE FROM research_sessions WHERE expires_at IS NOT NULL AND expires_at < NOW()");
  const expiresAt = workspaceId ? null : new Date(Date.now() + 7 * 24 * 60 * 60 * 1000);
  await db.query("INSERT INTO research_sessions (id, question, status, session, workspace_id, owner_uid, expires_at) VALUES ($1, $2, $3, $4::jsonb, $5, $6, $7) ON CONFLICT (id) DO UPDATE SET status = EXCLUDED.status, session = EXCLUDED.session, workspace_id = EXCLUDED.workspace_id, owner_uid = EXCLUDED.owner_uid, expires_at = EXCLUDED.expires_at, updated_at = NOW()", [session.id, session.question, session.status, JSON.stringify(session), workspaceId ?? null, ownerUid, expiresAt]);
  return { persisted: true };
}
export async function getSession(id: string, ownerUid: string): Promise<ResearchSession | undefined> { const db = database(); if (!db) return undefined; const result = await db.query<{ session: ResearchSession }>("SELECT session FROM research_sessions WHERE id = $1 AND owner_uid = $2 AND (expires_at IS NULL OR expires_at > NOW())", [id, ownerUid]); return result.rows[0]?.session; }

export async function listWorkspaces(ownerUid: string): Promise<Workspace[]> { const db = database(); if (!db) return []; const result = await db.query("SELECT id, name, description, created_at FROM research_workspaces WHERE owner_uid = $1 ORDER BY updated_at DESC", [ownerUid]); return result.rows.map((row) => ({ id: row.id, name: row.name, description: row.description, createdAt: row.created_at })); }
export async function createWorkspace(ownerUid: string, name: string, description = ""): Promise<Workspace> { const db = database(); if (!db) throw new Error("DATABASE_URL is required to create a workspace."); const id = crypto.randomUUID(); const result = await db.query("INSERT INTO research_workspaces (id, name, description, owner_uid) VALUES ($1, $2, $3, $4) RETURNING id, name, description, created_at", [id, name, description, ownerUid]); const row = result.rows[0]; return { id: row.id, name: row.name, description: row.description, createdAt: row.created_at }; }
export async function workspaceSessions(workspaceId: string, ownerUid: string): Promise<ResearchSession[]> { const db = database(); if (!db) return []; const result = await db.query<{ session: ResearchSession }>("SELECT session FROM research_sessions WHERE workspace_id = $1 AND owner_uid = $2 ORDER BY created_at DESC", [workspaceId, ownerUid]); return result.rows.map((row) => row.session); }
export async function listWorkspaceRuns(workspaceId: string, ownerUid: string): Promise<WorkspaceRun[]> { const db = database(); if (!db) return []; const result = await db.query<WorkspaceRun>("SELECT id, question, status, created_at AS \"createdAt\" FROM research_sessions WHERE workspace_id = $1 AND owner_uid = $2 AND (expires_at IS NULL OR expires_at > NOW()) ORDER BY created_at DESC", [workspaceId, ownerUid]); return result.rows; }
const mapPaper = (row: Record<string, unknown>): WorkspacePaper => ({ id: String(row.id), workspaceId: String(row.workspace_id), title: String(row.title), contentMarkdown: String(row.content_markdown), citations: Array.isArray(row.citations) ? row.citations : [], sourceSessionIds: Array.isArray(row.source_session_ids) ? row.source_session_ids as string[] : [], citationStyle: row.citation_style === "MLA" ? "MLA" : "APA", targetWordCount: Number(row.target_word_count), paperMetadata: row.paper_metadata as PaperMetadata, parentPaperId: typeof row.parent_paper_id === "string" ? row.parent_paper_id : undefined, revisionNumber: Number(row.revision_number || 1), createdAt: String(row.created_at) });
export async function savePaper(ownerUid: string, paper: Omit<WorkspacePaper, "id" | "createdAt" | "revisionNumber">): Promise<WorkspacePaper> { const db = database(); if (!db) throw new Error("DATABASE_URL is required to save a paper."); const id = crypto.randomUUID(); const revision = paper.parentPaperId ? await db.query<{ revision_number: number }>("SELECT COALESCE(MAX(revision_number), 0) + 1 AS revision_number FROM workspace_papers WHERE owner_uid = $1 AND (id = $2 OR parent_paper_id = $2)", [ownerUid, paper.parentPaperId]) : { rows: [{ revision_number: 1 }] }; const result = await db.query("INSERT INTO workspace_papers (id, workspace_id, title, content_markdown, citations, source_session_ids, owner_uid, citation_style, target_word_count, paper_metadata, parent_paper_id, revision_number) VALUES ($1, $2, $3, $4, $5::jsonb, $6::jsonb, $7, $8, $9, $10::jsonb, $11, $12) RETURNING id, workspace_id, title, content_markdown, citations, source_session_ids, citation_style, target_word_count, paper_metadata, parent_paper_id, revision_number, created_at", [id, paper.workspaceId, paper.title, paper.contentMarkdown, JSON.stringify(paper.citations), JSON.stringify(paper.sourceSessionIds), ownerUid, paper.citationStyle, paper.targetWordCount, JSON.stringify(paper.paperMetadata), paper.parentPaperId || null, revision.rows[0].revision_number]); return mapPaper(result.rows[0]); }
export async function listPapers(workspaceId: string, ownerUid: string): Promise<WorkspacePaper[]> { const db = database(); if (!db) return []; const result = await db.query("SELECT id, workspace_id, title, content_markdown, citations, source_session_ids, citation_style, target_word_count, paper_metadata, parent_paper_id, revision_number, created_at FROM workspace_papers WHERE workspace_id = $1 AND owner_uid = $2 ORDER BY updated_at DESC", [workspaceId, ownerUid]); return result.rows.map(mapPaper); }
export async function getPaper(id: string, ownerUid: string): Promise<WorkspacePaper | undefined> { const db = database(); if (!db) return undefined; const result = await db.query("SELECT id, workspace_id, title, content_markdown, citations, source_session_ids, citation_style, target_word_count, paper_metadata, parent_paper_id, revision_number, created_at FROM workspace_papers WHERE id = $1 AND owner_uid = $2", [id, ownerUid]); return result.rows[0] ? mapPaper(result.rows[0]) : undefined; }
export async function listWritingProfiles(ownerUid: string): Promise<WritingProfile[]> { const db = database(); if (!db) return []; const result = await db.query("SELECT id, name, author_name, course_name, instructor_name, citation_style, target_word_count FROM writing_profiles WHERE owner_uid = $1 ORDER BY updated_at DESC", [ownerUid]); return result.rows.map((row) => ({ id: row.id, name: row.name, authorName: row.author_name, courseName: row.course_name, instructorName: row.instructor_name, citationStyle: row.citation_style, targetWordCount: row.target_word_count })); }
export async function createWritingProfile(ownerUid: string, input: Partial<WritingProfile>): Promise<WritingProfile> { const db = database(); if (!db) throw new Error("DATABASE_URL is required to save a writing profile."); const style: CitationStyle = input.citationStyle === "MLA" ? "MLA" : "APA"; const count = Math.max(250, Math.min(10000, Number(input.targetWordCount) || 1000)); const id = crypto.randomUUID(); const result = await db.query("INSERT INTO writing_profiles (id, owner_uid, name, author_name, course_name, instructor_name, citation_style, target_word_count) VALUES ($1,$2,$3,$4,$5,$6,$7,$8) RETURNING id, name, author_name, course_name, instructor_name, citation_style, target_word_count", [id, ownerUid, String(input.name).trim(), input.authorName?.trim() || "", input.courseName?.trim() || "", input.instructorName?.trim() || "", style, count]); const row = result.rows[0]; return { id: row.id, name: row.name, authorName: row.author_name, courseName: row.course_name, instructorName: row.instructor_name, citationStyle: row.citation_style, targetWordCount: row.target_word_count }; }
export async function deleteWorkspace(id: string, ownerUid: string) { const db = database(); if (!db) throw new Error("DATABASE_URL is required to delete a workspace."); const result = await db.query("DELETE FROM research_workspaces WHERE id = $1 AND owner_uid = $2 RETURNING id", [id, ownerUid]); return Boolean(result.rowCount); }
export async function deleteSession(id: string, ownerUid: string) { const db = database(); if (!db) throw new Error("DATABASE_URL is required to delete a research session."); const result = await db.query("DELETE FROM research_sessions WHERE id = $1 AND owner_uid = $2 RETURNING id", [id, ownerUid]); return Boolean(result.rowCount); }
export async function deletePaper(id: string, ownerUid: string) { const db = database(); if (!db) throw new Error("DATABASE_URL is required to delete a paper."); const result = await db.query("DELETE FROM workspace_papers WHERE id = $1 AND owner_uid = $2 RETURNING id", [id, ownerUid]); return Boolean(result.rowCount); }
export async function deleteWritingProfile(id: string, ownerUid: string) { const db = database(); if (!db) throw new Error("DATABASE_URL is required to delete a writing profile."); const result = await db.query("DELETE FROM writing_profiles WHERE id = $1 AND owner_uid = $2 RETURNING id", [id, ownerUid]); return Boolean(result.rowCount); }
export async function accountLibrary(ownerUid: string) { const db = database(); if (!db) return { sessions: [], papers: [] }; const [sessions, papers] = await Promise.all([db.query("SELECT s.id, s.question, s.created_at, w.name AS workspace_name FROM research_sessions s LEFT JOIN research_workspaces w ON w.id = s.workspace_id WHERE s.owner_uid = $1 AND (s.expires_at IS NULL OR s.expires_at > NOW()) ORDER BY s.created_at DESC LIMIT 50", [ownerUid]), db.query("SELECT p.id, p.title, p.created_at, w.name AS workspace_name FROM workspace_papers p LEFT JOIN research_workspaces w ON w.id = p.workspace_id WHERE p.owner_uid = $1 ORDER BY p.created_at DESC LIMIT 50", [ownerUid])]); return { sessions: sessions.rows.map((row) => ({ id: row.id, title: row.question, workspaceName: row.workspace_name || "Unfiled", createdAt: row.created_at })), papers: papers.rows.map((row) => ({ id: row.id, title: row.title, workspaceName: row.workspace_name || "Deleted workspace", createdAt: row.created_at })) }; }
