import { Pool } from "pg";
import type { ResearchSession } from "./contracts";

export type Workspace = { id: string; name: string; description: string; createdAt: string };
export type WorkspacePaper = { id: string; workspaceId: string; title: string; contentMarkdown: string; citations: unknown[]; sourceSessionIds: string[]; createdAt: string };

let pool: Pool | undefined;
function database() { if (!process.env.DATABASE_URL) return undefined; pool ??= new Pool({ connectionString: process.env.DATABASE_URL }); return pool; }
export async function saveSession(session: ResearchSession, workspaceId?: string): Promise<{ persisted: boolean; reason?: string }> {
  const db = database(); if (!db) return { persisted: false, reason: "DATABASE_URL is not configured; session exists only for this request." };
  await db.query("INSERT INTO research_sessions (id, question, status, session, workspace_id) VALUES ($1, $2, $3, $4::jsonb, $5) ON CONFLICT (id) DO UPDATE SET status = EXCLUDED.status, session = EXCLUDED.session, workspace_id = EXCLUDED.workspace_id, updated_at = NOW()", [session.id, session.question, session.status, JSON.stringify(session), workspaceId ?? null]);
  return { persisted: true };
}
export async function getSession(id: string): Promise<ResearchSession | undefined> { const db = database(); if (!db) return undefined; const result = await db.query<{ session: ResearchSession }>("SELECT session FROM research_sessions WHERE id = $1", [id]); return result.rows[0]?.session; }

export async function listWorkspaces(): Promise<Workspace[]> { const db = database(); if (!db) return []; const result = await db.query("SELECT id, name, description, created_at FROM research_workspaces ORDER BY updated_at DESC"); return result.rows.map((row) => ({ id: row.id, name: row.name, description: row.description, createdAt: row.created_at })); }
export async function createWorkspace(name: string, description = ""): Promise<Workspace> { const db = database(); if (!db) throw new Error("DATABASE_URL is required to create a workspace."); const id = crypto.randomUUID(); const result = await db.query("INSERT INTO research_workspaces (id, name, description) VALUES ($1, $2, $3) RETURNING id, name, description, created_at", [id, name, description]); const row = result.rows[0]; return { id: row.id, name: row.name, description: row.description, createdAt: row.created_at }; }
export async function workspaceSessions(workspaceId: string): Promise<ResearchSession[]> { const db = database(); if (!db) return []; const result = await db.query<{ session: ResearchSession }>("SELECT session FROM research_sessions WHERE workspace_id = $1 ORDER BY created_at DESC", [workspaceId]); return result.rows.map((row) => row.session); }
export async function savePaper(paper: Omit<WorkspacePaper, "id" | "createdAt">): Promise<WorkspacePaper> { const db = database(); if (!db) throw new Error("DATABASE_URL is required to save a paper."); const id = crypto.randomUUID(); const result = await db.query("INSERT INTO workspace_papers (id, workspace_id, title, content_markdown, citations, source_session_ids) VALUES ($1, $2, $3, $4, $5::jsonb, $6::jsonb) RETURNING id, workspace_id, title, content_markdown, citations, source_session_ids, created_at", [id, paper.workspaceId, paper.title, paper.contentMarkdown, JSON.stringify(paper.citations), JSON.stringify(paper.sourceSessionIds)]); const row = result.rows[0]; return { id: row.id, workspaceId: row.workspace_id, title: row.title, contentMarkdown: row.content_markdown, citations: row.citations, sourceSessionIds: row.source_session_ids, createdAt: row.created_at }; }
export async function listPapers(workspaceId: string): Promise<WorkspacePaper[]> { const db = database(); if (!db) return []; const result = await db.query("SELECT id, workspace_id, title, content_markdown, citations, source_session_ids, created_at FROM workspace_papers WHERE workspace_id = $1 ORDER BY updated_at DESC", [workspaceId]); return result.rows.map((row) => ({ id: row.id, workspaceId: row.workspace_id, title: row.title, contentMarkdown: row.content_markdown, citations: row.citations, sourceSessionIds: row.source_session_ids, createdAt: row.created_at })); }
