import { Pool } from "pg";
import type { ResearchSession } from "./contracts";

export type Workspace = { id: string; name: string; description: string; createdAt: string };
export type CitationStyle = "APA" | "MLA";
export type PaperMetadata = { authorName: string; courseName: string; instructorName: string; date: string };
export type WorkspacePaper = { id: string; workspaceId: string; title: string; contentMarkdown: string; citations: unknown[]; sourceSessionIds: string[]; citationStyle: CitationStyle; targetWordCount: number; paperMetadata: PaperMetadata; createdAt: string };
export type WorkspaceRun = { id: string; question: string; status: ResearchSession["status"]; createdAt: string };
export type WritingProfile = { id: string; name: string; authorName: string; courseName: string; instructorName: string; citationStyle: CitationStyle; targetWordCount: number };

let pool: Pool | undefined;
function database() { if (!process.env.DATABASE_URL) return undefined; pool ??= new Pool({ connectionString: process.env.DATABASE_URL }); return pool; }
export async function saveSession(session: ResearchSession, ownerUid: string, workspaceId?: string): Promise<{ persisted: boolean; reason?: string }> {
  const db = database(); if (!db) return { persisted: false, reason: "DATABASE_URL is not configured; session exists only for this request." };
  if (workspaceId) { const workspace = await db.query("SELECT 1 FROM research_workspaces WHERE id = $1 AND owner_uid = $2", [workspaceId, ownerUid]); if (!workspace.rowCount) throw new Error("Workspace not found."); }
  await db.query("DELETE FROM research_sessions WHERE expires_at IS NOT NULL AND expires_at < NOW()");
  const expiresAt = workspaceId ? null : new Date(Date.now() + 7 * 24 * 60 * 60 * 1000);
  await db.query("INSERT INTO research_sessions (id, question, status, session, workspace_id, owner_uid, expires_at) VALUES ($1, $2, $3, $4::jsonb, $5, $6, $7) ON CONFLICT (id) DO UPDATE SET status = EXCLUDED.status, session = EXCLUDED.session, workspace_id = EXCLUDED.workspace_id, owner_uid = EXCLUDED.owner_uid, expires_at = EXCLUDED.expires_at, updated_at = NOW()", [session.id, session.question, session.status, JSON.stringify(session), workspaceId ?? null, ownerUid, expiresAt]);
  return { persisted: true };
}
export async function getSession(id: string, ownerUid: string): Promise<ResearchSession | undefined> { const db = database(); if (!db) return undefined; const result = await db.query<{ session: ResearchSession }>("SELECT session FROM research_sessions WHERE id = $1 AND owner_uid = $2 AND (expires_at IS NULL OR expires_at > NOW())", [id, ownerUid]); return result.rows[0]?.session; }

export async function listWorkspaces(ownerUid: string): Promise<Workspace[]> { const db = database(); if (!db) return []; const result = await db.query("SELECT id, name, description, created_at FROM research_workspaces WHERE owner_uid = $1 ORDER BY updated_at DESC", [ownerUid]); return result.rows.map((row) => ({ id: row.id, name: row.name, description: row.description, createdAt: row.created_at })); }
export async function createWorkspace(ownerUid: string, name: string, description = ""): Promise<Workspace> { const db = database(); if (!db) throw new Error("DATABASE_URL is required to create a workspace."); const id = crypto.randomUUID(); const result = await db.query("INSERT INTO research_workspaces (id, name, description, owner_uid) VALUES ($1, $2, $3, $4) RETURNING id, name, description, created_at", [id, name, description, ownerUid]); const row = result.rows[0]; return { id: row.id, name: row.name, description: row.description, createdAt: row.created_at }; }
export async function workspaceSessions(workspaceId: string, ownerUid: string): Promise<ResearchSession[]> { const db = database(); if (!db) return []; const result = await db.query<{ session: ResearchSession }>("SELECT session FROM research_sessions WHERE workspace_id = $1 AND owner_uid = $2 ORDER BY created_at DESC", [workspaceId, ownerUid]); return result.rows.map((row) => row.session); }
export async function listWorkspaceRuns(workspaceId: string, ownerUid: string): Promise<WorkspaceRun[]> { const db = database(); if (!db) return []; const result = await db.query<WorkspaceRun>("SELECT id, question, status, created_at AS \"createdAt\" FROM research_sessions WHERE workspace_id = $1 AND owner_uid = $2 AND (expires_at IS NULL OR expires_at > NOW()) ORDER BY created_at DESC", [workspaceId, ownerUid]); return result.rows; }
export async function savePaper(ownerUid: string, paper: Omit<WorkspacePaper, "id" | "createdAt">): Promise<WorkspacePaper> { const db = database(); if (!db) throw new Error("DATABASE_URL is required to save a paper."); const id = crypto.randomUUID(); const result = await db.query("INSERT INTO workspace_papers (id, workspace_id, title, content_markdown, citations, source_session_ids, owner_uid, citation_style, target_word_count, paper_metadata) VALUES ($1, $2, $3, $4, $5::jsonb, $6::jsonb, $7, $8, $9, $10::jsonb) RETURNING id, workspace_id, title, content_markdown, citations, source_session_ids, citation_style, target_word_count, paper_metadata, created_at", [id, paper.workspaceId, paper.title, paper.contentMarkdown, JSON.stringify(paper.citations), JSON.stringify(paper.sourceSessionIds), ownerUid, paper.citationStyle, paper.targetWordCount, JSON.stringify(paper.paperMetadata)]); const row = result.rows[0]; return { id: row.id, workspaceId: row.workspace_id, title: row.title, contentMarkdown: row.content_markdown, citations: row.citations, sourceSessionIds: row.source_session_ids, citationStyle: row.citation_style, targetWordCount: row.target_word_count, paperMetadata: row.paper_metadata, createdAt: row.created_at }; }
export async function listPapers(workspaceId: string, ownerUid: string): Promise<WorkspacePaper[]> { const db = database(); if (!db) return []; const result = await db.query("SELECT id, workspace_id, title, content_markdown, citations, source_session_ids, citation_style, target_word_count, paper_metadata, created_at FROM workspace_papers WHERE workspace_id = $1 AND owner_uid = $2 ORDER BY updated_at DESC", [workspaceId, ownerUid]); return result.rows.map((row) => ({ id: row.id, workspaceId: row.workspace_id, title: row.title, contentMarkdown: row.content_markdown, citations: row.citations, sourceSessionIds: row.source_session_ids, citationStyle: row.citation_style, targetWordCount: row.target_word_count, paperMetadata: row.paper_metadata, createdAt: row.created_at })); }
export async function listWritingProfiles(ownerUid: string): Promise<WritingProfile[]> { const db = database(); if (!db) return []; const result = await db.query("SELECT id, name, author_name, course_name, instructor_name, citation_style, target_word_count FROM writing_profiles WHERE owner_uid = $1 ORDER BY updated_at DESC", [ownerUid]); return result.rows.map((row) => ({ id: row.id, name: row.name, authorName: row.author_name, courseName: row.course_name, instructorName: row.instructor_name, citationStyle: row.citation_style, targetWordCount: row.target_word_count })); }
export async function createWritingProfile(ownerUid: string, input: Partial<WritingProfile>): Promise<WritingProfile> { const db = database(); if (!db) throw new Error("DATABASE_URL is required to save a writing profile."); const style: CitationStyle = input.citationStyle === "MLA" ? "MLA" : "APA"; const count = Math.max(250, Math.min(10000, Number(input.targetWordCount) || 1000)); const id = crypto.randomUUID(); const result = await db.query("INSERT INTO writing_profiles (id, owner_uid, name, author_name, course_name, instructor_name, citation_style, target_word_count) VALUES ($1,$2,$3,$4,$5,$6,$7,$8) RETURNING id, name, author_name, course_name, instructor_name, citation_style, target_word_count", [id, ownerUid, String(input.name).trim(), input.authorName?.trim() || "", input.courseName?.trim() || "", input.instructorName?.trim() || "", style, count]); const row = result.rows[0]; return { id: row.id, name: row.name, authorName: row.author_name, courseName: row.course_name, instructorName: row.instructor_name, citationStyle: row.citation_style, targetWordCount: row.target_word_count }; }
